Esp32 s3
hideakitai/ESP32DMASPI pull request #28
Opened 2023-01-31 16:38 UTC by s-light

fixes #27

2023-08-08 00:50 UTC, hideakitai requested changes

2023-08-08 00:50 UTC, hideakitai commented on examples/master_simple/debug.cfg
Could you remove unnecessary files for this library?

2023-08-08 00:50 UTC, hideakitai commented on examples/master_simple/debug_custom.json
Could you remove unnecessary files for this library?

2023-08-08 00:50 UTC, hideakitai commented on examples/master_simple/esp32s3.svd
Could you remove unnecessary files for this library?

2023-08-08 00:50 UTC, hideakitai commented on ESP32DMASPIMaster.h
> +// TODO check ESP32C3
Could you also support ESP32C3?

2023-08-13 09:49 UTC, hideakitai commented
Fixed by https://github.com/hideakitai/ESP32DMASPI/pull/31

2023-08-13 09:49 UTC, closed without merging

2023-08-14 14:28 UTC, s-light commented
thanks for making it work.
sorry for not seeing your requests.